# Generated by Django 5.0.4 on 2024-04-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QP_Uploader',
            fields=[
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board', models.CharField(max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Papers',
            fields=[
                ('QP_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('QP_Name', models.CharField(max_length=50)),
                ('QP_UploadDate', models.DateField()),
                ('QP_Subject', models.CharField(max_length=10)),
                ('QP_Language', models.CharField(max_length=10)),
                ('QP_Board', models.CharField(max_length=10)),
                ('QP_Grade', models.IntegerField()),
                ('QP_UploaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.qp_uploader')),
            ],
        ),
        migrations.CreateModel(
            name='QP_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Marks', models.IntegerField()),
                ('Group_Size', models.IntegerField()),
                ('QP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.question_papers')),
            ],
        ),
    ]
