# Generated by Django 5.0.3 on 2024-06-22 13:33

import evaluators_qpuploaders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators_qpuploaders', '0002_question_papers_qp_file_alter_evaluator_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_papers',
            name='QP_File',
            field=models.FileField(upload_to='question_papers', validators=[evaluators_qpuploaders.models.validate_pdf]),
        ),
    ]
