# Generated by Django 5.0.4 on 2024-04-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('evaluators_qpuploaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('Grade', models.IntegerField()),
                ('Board', models.CharField(max_length=10)),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_mentors.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Recommended_QPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDone', models.BooleanField()),
                ('RecommendedTime', models.DateTimeField()),
                ('MentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_mentors.mentor')),
                ('QP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators_qpuploaders.question_papers')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_mentors.student')),
            ],
        ),
    ]
